language: go
go:
  - 1.6
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
script: ginkgo -r -randomizeSuites -randomizeAllSpecs -race
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: cde253b3c0caf533b147ca7a4273806d6eca182730398980cc6b400929b38400
