// Code generated by counterfeiter. DO NOT EDIT.
package actorfakes

import (
	"sync"

	"github.com/goodmustache/pt/actor"
	"github.com/goodmustache/pt/tracker"
)

type FakeTrackerClient struct {
	MeStub        func() (tracker.Me, error)
	meMutex       sync.RWMutex
	meArgsForCall []struct {
	}
	meReturns struct {
		result1 tracker.Me
		result2 error
	}
	meReturnsOnCall map[int]struct {
		result1 tracker.Me
		result2 error
	}
	ProjectsStub        func() ([]tracker.Project, error)
	projectsMutex       sync.RWMutex
	projectsArgsForCall []struct {
	}
	projectsReturns struct {
		result1 []tracker.Project
		result2 error
	}
	projectsReturnsOnCall map[int]struct {
		result1 []tracker.Project
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTrackerClient) Me() (tracker.Me, error) {
	fake.meMutex.Lock()
	ret, specificReturn := fake.meReturnsOnCall[len(fake.meArgsForCall)]
	fake.meArgsForCall = append(fake.meArgsForCall, struct {
	}{})
	fake.recordInvocation("Me", []interface{}{})
	fake.meMutex.Unlock()
	if fake.MeStub != nil {
		return fake.MeStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.meReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTrackerClient) MeCallCount() int {
	fake.meMutex.RLock()
	defer fake.meMutex.RUnlock()
	return len(fake.meArgsForCall)
}

func (fake *FakeTrackerClient) MeCalls(stub func() (tracker.Me, error)) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = stub
}

func (fake *FakeTrackerClient) MeReturns(result1 tracker.Me, result2 error) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = nil
	fake.meReturns = struct {
		result1 tracker.Me
		result2 error
	}{result1, result2}
}

func (fake *FakeTrackerClient) MeReturnsOnCall(i int, result1 tracker.Me, result2 error) {
	fake.meMutex.Lock()
	defer fake.meMutex.Unlock()
	fake.MeStub = nil
	if fake.meReturnsOnCall == nil {
		fake.meReturnsOnCall = make(map[int]struct {
			result1 tracker.Me
			result2 error
		})
	}
	fake.meReturnsOnCall[i] = struct {
		result1 tracker.Me
		result2 error
	}{result1, result2}
}

func (fake *FakeTrackerClient) Projects() ([]tracker.Project, error) {
	fake.projectsMutex.Lock()
	ret, specificReturn := fake.projectsReturnsOnCall[len(fake.projectsArgsForCall)]
	fake.projectsArgsForCall = append(fake.projectsArgsForCall, struct {
	}{})
	fake.recordInvocation("Projects", []interface{}{})
	fake.projectsMutex.Unlock()
	if fake.ProjectsStub != nil {
		return fake.ProjectsStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.projectsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeTrackerClient) ProjectsCallCount() int {
	fake.projectsMutex.RLock()
	defer fake.projectsMutex.RUnlock()
	return len(fake.projectsArgsForCall)
}

func (fake *FakeTrackerClient) ProjectsCalls(stub func() ([]tracker.Project, error)) {
	fake.projectsMutex.Lock()
	defer fake.projectsMutex.Unlock()
	fake.ProjectsStub = stub
}

func (fake *FakeTrackerClient) ProjectsReturns(result1 []tracker.Project, result2 error) {
	fake.projectsMutex.Lock()
	defer fake.projectsMutex.Unlock()
	fake.ProjectsStub = nil
	fake.projectsReturns = struct {
		result1 []tracker.Project
		result2 error
	}{result1, result2}
}

func (fake *FakeTrackerClient) ProjectsReturnsOnCall(i int, result1 []tracker.Project, result2 error) {
	fake.projectsMutex.Lock()
	defer fake.projectsMutex.Unlock()
	fake.ProjectsStub = nil
	if fake.projectsReturnsOnCall == nil {
		fake.projectsReturnsOnCall = make(map[int]struct {
			result1 []tracker.Project
			result2 error
		})
	}
	fake.projectsReturnsOnCall[i] = struct {
		result1 []tracker.Project
		result2 error
	}{result1, result2}
}

func (fake *FakeTrackerClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.meMutex.RLock()
	defer fake.meMutex.RUnlock()
	fake.projectsMutex.RLock()
	defer fake.projectsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeTrackerClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ actor.TrackerClient = new(FakeTrackerClient)
